# -*- coding: utf-8 -*-
"""testeDesafioEntrevista.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VavLHyL9N7d6gGfGJ4yidvGSKZ1k4y85
"""

import pandas as pd

class Aluno:

  def __init__(self, nome, matricula, telefone, email, uffmail, status):
    self.nome = nome
    self.matricula = matricula
    self.telefone = telefone
    self.email = email
    self.uffmail = uffmail
    self.status = status

  def esta_ativo(self):
    return self.status.lower() == "ativo"

  def tem_uffmail(self):
    return self.uffmail != ""


def criar_emails(nome):

  separar_nome = nome.split()
  apelido = separar_nome[0].lower()
  sobrenome = separar_nome[-1].lower()

  opcoes = [ apelido + "_" + sobrenome + "@id.uff.br",
      apelido + sobrenome + "@id.uff.br", sobrenome + apelido + "@id.uff.br",
  ]

  return opcoes


def enviar_sms(telefone, email):

  print("Seu IDUFF", email, "foi criado com sucesso")
  print("Um SMS foi enviado para", telefone, "com sua senha de acesso.")


arquivo = pd.read_csv("alunos.csv")

matricula_escolhida = int(input("Digite a matrícula do aluno: "))

aluno_encontrado = None

for index, row in arquivo.iterrows():

  nome = row["nome"]
  matricula = row["matricula"]
  telefone = row["telefone"]
  email = row["email"]
  uffmail = row["uffmail"] if pd.notna(row["uffmail"]) else ""
  status = row["status"]

  aluno = Aluno(nome, matricula, telefone, email, uffmail, status)

  if aluno.matricula == matricula_escolhida:

    if not aluno.esta_ativo():
      print("Aluno não está ativo")
      break

    if aluno.tem_uffmail():
      print("Aluno já possui IDUFF")
      break

    aluno_encontrado = aluno
    break


if aluno_encontrado:

  opcoes = criar_emails(aluno_encontrado.nome)

  print("Opções de email:")

  for i, op in enumerate(opcoes):
    print(i, op)

  escolha = int(input("Escolha uma opção: "))

  email_escolhido = opcoes[escolha]

  aluno_encontrado.uffmail = email_escolhido

  enviar_sms(aluno_encontrado.telefone, email_escolhido)

else:
  print("Matrícula não encontrada.")

